name: Deploy to Vercel

on:
  push:
    branches:
      - release

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Vercel (Production)
        run: |
          npx vercel --prod --yes \
            --token "${{ secrets.VERCEL_TOKEN }}" \
            --scope team_3rfQLaR5QHz7LpFAousps1SI
